from django.urls import path
from adminpanel import views

urlpatterns = [
    path('', views.admin, name='admin'),
    path('films/', views.films, name='films'),
    path('addfilm/', views.add_film, name='add_film'),
    path('edit/<int:pk>', views.UpdateFilmView.as_view(), name='editfilm'),
    path('delete_film/<int:pk>', views.FilmDeleteView.as_view(), name='delete_film'),
    path('cinemas/', views.cinemas, name='cinemas'),
    path('addcinema/', views.add_cinema, name='add_cinema'),
    path('cinema/<int:cinema_id>', views.cinema_info, name='cinema_info'),
    path('editcinema/<int:pk>', views.UpdateCinemaView.as_view(), name='edit_cinema'),
    path('cinema/<int:cinema_id>/addhall', views.add_cinema_hall, name='add_hall'),
    path('cinema/hall/<int:hall_id>', views.hall_info, name='hall_info'),
    path('edit_hall/<int:pk>', views.UpdateCinemaHallView.as_view(), name='edit_hall'),
    path('news/', views.news_list, name='news'),
    path('addnews/', views.add_news, name='add_news'),
    path('editnews/<int:pk>', views.UpdateNewsView.as_view(), name='edit_news'),
    path('stocks/', views.stocks, name='stocks'),
    path('addstock/', views.add_stock, name='add_stock'),
    path('editstock/<int:pk>', views.UpdateStockView.as_view(), name='edit_stock'),
    path('deletedone/', views.delete_done, name='delete_done'),
    path('delete_hall/<int:pk>', views.HallDeleteView.as_view(), name='delete_hall'),
    path('delete_news/<int:pk>', views.NewsDeleteView.as_view(), name='delete_news'),
    path('delete_stock/<int:pk>', views.StockDeleteView.as_view(), name='delete_stock'),
    path('pages/', views.pages, name='pages'),
    path('addpage/', views.add_page, name='add_page'),
    path('editpage/<int:pk>', views.UpdatePageView.as_view(), name='edit_page'),
    path('editmainpage/<int:pk>', views.UpdateMainPageView.as_view(), name='edit_mainpage'),
    path('contact/', views.ContactCinemaList, name='contact'),
    path('hall/<int:hall_id>/addsessionfilm/', views.add_film_session, name='add_filmsession'),
    path('bannersandsliders/', views.banners_and_sliders, name='bannersandsliders'),
    path('mailing/', views.mailing, name='mailing'),
    path('email/', views.contact_view, name='email'),
    path('success/', views.success_view, name='success'),
    path('select_user_contact/', views.select_user_contact, name='select_user_contact'),
    path('delete_slider/<int:pk>', views.SliderDeleteView.as_view(), name='delete_slider'),
    path('delete_background/<int:pk>', views.BackgroundDeleteView.as_view(), name='delete_background'),
    path('delete_newsslider/<int:pk>', views.NewsSliderDeleteView.as_view(), name='delete_newsslider'),
    path('addcontactcinema/', views.add_contact_cinema, name='add_contact_cinema'),
    path('editcontactcinema/<int:pk>', views.UpdateContactCinemaView.as_view(), name='edit_contact_cinema'),
    path('deletecontactcinema/<int:pk>', views.ContactCinemaDeleteView.as_view(), name='delete_contact_cinema'),
    path('deletepage/<int:pk>', views.PageDeleteView.as_view(), name='delete_page'),
    path('save_phone_sms/', views.save_phone_sms, name='save_phones'),

]
