# Generated by Django 3.2.4 on 2021-07-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_auto_20210726_1115'),
        ('userpage', '0003_delete_timeslotseatrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveAndBuySeats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reserve_seats', models.JSONField(null=True, verbose_name='Зарезервированые места')),
                ('buy_seats', models.JSONField(null=True, verbose_name='Купленные места')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.filmsession')),
            ],
        ),
    ]
