# Generated by Django 3.2.4 on 2021-08-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_backgroundsetting'),
        ('userpage', '0004_reserveandbuyseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatsReserveAndBuy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('seat', models.CharField(max_length=16, verbose_name='Место')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.filmsession')),
                ('status_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.statusseat')),
            ],
        ),
        migrations.DeleteModel(
            name='ReserveAndBuySeats',
        ),
    ]
