# Generated by Django 3.2.4 on 2021-06-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Format_film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Формат фильма')),
            ],
        ),
        migrations.CreateModel(
            name='Genre_film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Seo_block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Статус фильма')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('film_name', models.CharField(max_length=64, verbose_name='Название фильма')),
                ('relese_year', models.DateField(verbose_name='Год выхода')),
                ('country', models.CharField(max_length=64, verbose_name='Страна производитель')),
                ('producer', models.CharField(max_length=255, verbose_name='Продюсер')),
                ('director', models.CharField(max_length=255, verbose_name='Режисер')),
                ('screenwriter', models.CharField(max_length=255, verbose_name='Сценарист')),
                ('composer', models.CharField(max_length=255, verbose_name='Композитор')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('budget', models.CharField(max_length=64, verbose_name='Бюджет')),
                ('age', models.CharField(max_length=64, verbose_name='Возраст просмотра')),
                ('time_film', models.CharField(max_length=64, verbose_name='Длительность фильма')),
                ('description_film', models.TextField(verbose_name='Описание фильма')),
                ('main_picture', models.ImageField(height_field=200, upload_to='../static/img/film', width_field=100)),
                ('date_premiere', models.DateField(verbose_name='Дата примьеры')),
                ('trailer', models.URLField(verbose_name='Трейлер фильма')),
                ('format_film', models.ManyToManyField(to='adminpanel.Format_film')),
                ('genre', models.ManyToManyField(to='adminpanel.Genre_film')),
                ('status_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.status_film')),
            ],
        ),
    ]
