# Generated by Django 3.2.4 on 2021-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='main_picture',
            field=models.ImageField(height_field=295, upload_to='../static/img/film', width_field=200),
        ),
    ]
