# Generated by Django 3.2.4 on 2021-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_film_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='relese_year',
            field=models.CharField(max_length=64, verbose_name='Год выхода'),
        ),
    ]
