# Generated by Django 3.2.4 on 2021-06-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_film_relese_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cinema_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='conditions',
            field=models.TextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_cinema',
            field=models.TextField(null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/img/cinema'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='top_banner',
            field=models.ImageField(null=True, upload_to='static/img/cinema'),
        ),
    ]
