# Generated by Django 3.2.4 on 2021-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20210628_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema_hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number_hall', models.CharField(max_length=16, verbose_name='Номер зала')),
                ('create_date', models.DateTimeField()),
                ('description_hall', models.TextField(verbose_name='Описание зала')),
                ('top_banner', models.ImageField(upload_to='static/img/cinema/hall')),
                ('row', models.IntegerField(verbose_name='Количесво рядов')),
                ('col', models.IntegerField(verbose_name='Количесов мест в ряду')),
            ],
        ),
    ]
