# Generated by Django 3.2.4 on 2021-06-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_cinema_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_hall',
            name='cinema_id',
            field=models.IntegerField(null=True, verbose_name='Ид зала'),
        ),
    ]
