# Generated by Django 3.2.4 on 2021-06-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_cinema_hall_cinema_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema_hall',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
