# Generated by Django 3.2.4 on 2021-07-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_imagefilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='picture_1',
            field=models.ImageField(null=True, upload_to='static/img/film'),
        ),
        migrations.AddField(
            model_name='film',
            name='picture_2',
            field=models.ImageField(null=True, upload_to='static/img/film'),
        ),
        migrations.AddField(
            model_name='film',
            name='picture_3',
            field=models.ImageField(null=True, upload_to='static/img/film'),
        ),
        migrations.AddField(
            model_name='film',
            name='picture_4',
            field=models.ImageField(null=True, upload_to='static/img/film'),
        ),
        migrations.AddField(
            model_name='film',
            name='picture_5',
            field=models.ImageField(null=True, upload_to='static/img/film'),
        ),
        migrations.DeleteModel(
            name='ImageFilm',
        ),
    ]
