# Generated by Django 3.2.4 on 2021-07-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_news_status_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_stock', models.CharField(max_length=64, verbose_name='Название акции')),
                ('description_stock', models.TextField(verbose_name='Описание акции')),
                ('main_picture', models.ImageField(null=True, upload_to='static/img/cinema/stock')),
                ('picture_1', models.ImageField(null=True, upload_to='static/img/cinema/stock')),
                ('picture_2', models.ImageField(null=True, upload_to='static/img/cinema/stock')),
                ('picture_3', models.ImageField(null=True, upload_to='static/img/cinema/stock')),
                ('picture_4', models.ImageField(null=True, upload_to='static/img/cinema/stock')),
                ('picture_5', models.ImageField(null=True, upload_to='static/img/cinema/stock')),
                ('url_youtube', models.URLField(null=True, verbose_name='Видео акции')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField(verbose_name='Дата активации')),
                ('status_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.status_main')),
            ],
        ),
    ]
