# Generated by Django 3.2.4 on 2021-07-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_delete', models.ImageField(default=1, upload_to='', verbose_name='Возможность удаления')),
                ('name_page', models.CharField(max_length=32, verbose_name='Название страницы')),
                ('description_page', models.TextField(verbose_name='Описание')),
                ('main_picture', models.ImageField(null=True, upload_to='static/img/cinema/pages')),
                ('picture_1', models.ImageField(null=True, upload_to='static/img/cinema/pages')),
                ('picture_2', models.ImageField(null=True, upload_to='static/img/cinema/pages')),
                ('picture_3', models.ImageField(null=True, upload_to='static/img/cinema/pages')),
                ('picture_4', models.ImageField(null=True, upload_to='static/img/cinema/pages')),
                ('picture_5', models.ImageField(null=True, upload_to='static/img/cinema/pages')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.status_main')),
            ],
        ),
    ]
