# Generated by Django 3.2.4 on 2021-07-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_delete', models.ImageField(default=0, upload_to='', verbose_name='Возможность удаления')),
                ('name_page', models.CharField(default='Главная страница', max_length=32, verbose_name='Название страницы')),
                ('phone_one', models.CharField(max_length=32, verbose_name='Номер телефона 1')),
                ('phone_two', models.CharField(max_length=32, verbose_name='Номер телефона 2')),
                ('seo_text', models.TextField(verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.status_main')),
            ],
        ),
    ]
