# Generated by Django 3.2.4 on 2021-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='status_delete',
            field=models.IntegerField(default=0, verbose_name='Возможность удаления'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status_delete',
            field=models.IntegerField(default=1, verbose_name='Возможность удаления'),
        ),
    ]
