# Generated by Django 3.2.4 on 2021-07-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_auto_20210720_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_delete', models.IntegerField(default=0, verbose_name='Возможность удаления')),
                ('name_page', models.CharField(default='Контакты', max_length=32, verbose_name='Название страницы')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.status_main')),
            ],
        ),
    ]
