# Generated by Django 3.2.4 on 2021-07-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_auto_20210726_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='static/img/sliders')),
                ('url', models.URLField(null=True, verbose_name='Ссылка с картинки')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='budget',
            field=models.CharField(blank=True, default='-', max_length=64, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='film',
            name='composer',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Композитор'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='operator',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Продюсер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='screenwriter',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Сценарист'),
        ),
    ]
