# Generated by Django 3.2.4 on 2021-07-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_auto_20210730_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/sliders'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка с картинки'),
        ),
    ]
