# Generated by Django 3.2.4 on 2021-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_auto_20210730_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndStocksBanners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/img/sliders')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка с картинки')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
