# Generated by Django 3.2.4 on 2021-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_newsandstocksbanners'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundOn', models.IntegerField(default=0, verbose_name='Флаг включения фона')),
                ('backgroundDefault', models.ImageField(default='static/img/default/background-default.jpeg', upload_to='', verbose_name='Дефолтная картинка')),
                ('backgroundImg', models.ImageField(blank=True, default='static/img/default/background-default.jpeg', null=True, upload_to='static/img/default', verbose_name='Загружаемая картинка фона')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
