# Generated by Django 3.2.4 on 2021-08-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_contactcinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Видео новости'),
        ),
        migrations.AlterField(
            model_name='page',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/pages'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/cinema/stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='url_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Видео акции'),
        ),
    ]
