# Generated by Django 3.2.4 on 2021-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_autosms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcinema',
            name='coordinates',
            field=models.TextField(verbose_name='Координаты'),
        ),
    ]
