# Generated by Django 3.2.4 on 2021-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_alter_contactcinema_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='film',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
