# Generated by Django 3.2.4 on 2021-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_auto_20210811_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.CharField(max_length=32, verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=32, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default=0, max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.CharField(default=1, max_length=32, verbose_name='Польователь'),
        ),
    ]
