# Generated by Django 3.2.4 on 2021-08-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_auto_20210811_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmsession',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.status_main'),
        ),
        migrations.AlterField(
            model_name='autosms',
            name='id_group',
            field=models.IntegerField(default=1, verbose_name='Ид группы рассылки'),
        ),
    ]
