# Generated by Django 3.2.4 on 2021-08-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_auto_20210812_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_group', models.IntegerField(default=1, verbose_name='Ид группы рассылки')),
                ('email', models.EmailField(max_length=64, verbose_name='Email отправки')),
                ('template_mail', models.TextField(blank=True, null=True, verbose_name='Текст рассылки')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
